AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  elliotFunction

  Aws Lambda with fastapi and microserver

Parameters:
  Database:
    Type: String
  CastUrl:
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    Layers:
      - !Ref SharedLayer
    Environment:
      Variables:
        DATABASE_URI: !Ref Database

Resources:
  RouteApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Demo
      EndpointConfiguration: REGIONAL

  MoviesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Base:
          Properties:
            RestApiId:
              Ref: RouteApi
            Path: /api/v1/movies
            Method: ANY
          Type: Api
        Others:
          Properties:
            RestApiId:
              Ref: RouteApi
            Path: /api/v1/movies/{proxy+}
            Method: ANY
          Type: Api
      FunctionName: elliot-fastapi-movies
      CodeUri: microservices/movie_service/
      Handler: app.main.handler
      Environment:
        Variables:
          CAST_SERVICE_HOST_URL: !Ref CastUrl

  CastsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        Base:
          Properties:
            RestApiId:
              Ref: RouteApi
            Path: /api/v1/casts
            Method: ANY
          Type: Api
        Others:
          Properties:
            RestApiId:
              Ref: RouteApi
            Path: /api/v1/casts/{proxy+}
            Method: ANY
          Type: Api
      FunctionName: elliot-fastapi-casts
      CodeUri: microservices/cast_service/
      Handler: app.main.handler

  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: elliot-demo-shared
      Description: common dependencies
      ContentUri: shared/
      LicenseInfo: 'MIT'
      RetentionPolicy: Delete
